apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: default
  labels:
    app: devops-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: 524183713945.dkr.ecr.us-east-1.amazonaws.com/devops-ecr-repo:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
  namespace: default
  labels:
    app: devops-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: devops-service
